In [1]:
import numpy as np
from sympy import *

x=Symbol("x")
y=Symbol("y")
z=Symbol("z")
w=Symbol("w")

a=np.matrix([[x,y],[z,w]])
print(a)

[[x y]
 [z w]]


In [234]:
def adj(a):
    global a_new
    if a.shape[0]==a.shape[1]:
        pass
    elif a.shape[0]!=a.shape[1]:
        print("nah cunt try again")
    c_=[]
    for i in range(a.shape[0]):
        c=np.copy(a)
        for j in range(a.shape[0]):
            c_i=np.delete(c,j,0)
            c_i=np.delete(c_i,i,1)
            c_a=np.linalg.det(c_i)
            c_.append(c_a)
    #print(c_)
    c_new=[]
    if a.shape[0]%2==0:
        #print("not done yet")
        for i in range(a.shape[0]):
            #print(int(len(c_))/a.shape[0])
            mul=int(i*(int(len(c_))/a.shape[0]))
            #print(mul%2)
            if i%2==0:
                for j in range(a.shape[0]):
                    if j%2==0:
                        c_new.append(1*c_[j+mul])
                    elif j%2==1:
                        c_new.append(-1*c_[j+mul])
            elif i%2==1:
                for j in range(a.shape[0]):
                    if j%2==0:
                        c_new.append(-1*c_[j+mul])
                    elif j%2==1:
                        c_new.append(1*c_[j+mul])
            #print(c_new)
        a_new=np.array(c_new).reshape((a.shape[0],a.shape[0]))
    #print(a_new)
    elif a.shape[0]%2==1:
        for i in range(int(len(c_))):
            if i%2==0:
                c_new.append(1*c_[i])
            elif i%2==1:
                c_new.append(-1*c_[i])
        a_new=np.array(c_new).reshape((a.shape[0],a.shape[0]))
    #print(a_new)
    
yep=np.matrix([[27,47,21,48],[12,6,16,4],[19,43,21,10],[18,53,2,8]])
adj(yep)

In [246]:
peep=np.matrix([[0.3,0.15,0.21,0.48],[1.42,0.46,1.16,0.91],[0.19,0.43,0.13,1.70],[1.28,0.53,1.41,0.28]])
adj(peep)
print(a_new)
print(np.linalg.det(yep))

[[ 0.308654 -0.067788 -0.053286  0.014712]
 [ 0.797239 -0.213672 -0.121974  0.068295]
 [-0.541191  0.131616  0.087654 -0.032181]
 [-0.194766  0.051558  0.033072 -0.016458]]
243719.99999999983


In [160]:
b=np.matrix([[1,3,2],[4,5,6],[7,8,9]])
#print(b)
#print(b.shape[1])
#print(len(b))
c_=[]
for i in range(b.shape[0]):
    c=np.copy(b)
    #print(i)
    #print(b[i+1:])
    #print(b[0,i])
    #c_n=np.delete(c,0,0)
    for j in range(b.shape[0]):
        #print(c[i,j])
        #print(b[j,i])
        #c_n=np.delete(c,i,j)
        c_i=np.delete(c,j,0)
        c_i=np.delete(c_i,i,1)
        c_a=round(np.linalg.det(c_i))
        c_.append(c_a)
#print(c_)
#print(c_i)
#print(c_a)
#print(c_)
#print(round(c_[0]))
yep=3
c_new=[]
for i in range(len(c_)):
    if i%2==0:
        #print(-1*c_[i])
        c_new.append(1*c_[i])
        
    elif i%2==1:
        #print(-1*c_[i])
        c_new.append(-1*c_[i])
        
#print(c_new)

b_new=np.array(c_new).reshape((b.shape[0],b.shape[0]))
print(b_new)

det_b=round(np.linalg.det(b))

print(det_b)

inv_b=(1/(np.linalg.det(b)))*b_new
print(inv_b)

print("\n")
prod_unf=b*inv_b
yeh=[]
for i in range(b.shape[0]):
    for j in range(b.shape[0]):
        yeh.append(round(prod_unf[i,j]))
prod=np.array(yeh).reshape((b.shape[0],b.shape[0]))
print(prod)

check=np.identity(b.shape[0])

if prod.all()==check.all():
    print("W")

[[ -3 -11   8]
 [  6  -5   2]
 [ -3  13  -7]]
9
[[-0.33333333 -1.22222222  0.88888889]
 [ 0.66666667 -0.55555556  0.22222222]
 [-0.33333333  1.44444444 -0.77777778]]


[[1 0 0]
 [0 1 0]
 [0 0 1]]
W


In [127]:
c2=[]
#print(c_)
c_n=np.matrix([[5,6],[8,9]])
c_q=np.linalg.det(c_n)
#print(c_n)
#print(c_q)
c2.append(c_q)

c_ewe=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
#print(np.delete(c_ewe,0,0))
print(c_ewe)
#c_fl=c_ewe.flatten()
#print(c_fl[0])
#for i in range(c_ewe.shape[0]):
#    #print(c_fl)
#    c_fl=np.delete(c_fl,i)
#print(c_fl)

for i in range(c_ewe.shape[0]):
    #print(c_fl)
    #c_f=np.delete(c_ewe,i,0)
    for j in range(c_ewe.shape[0]):
        c_f=np.delete(c_ewe,j,0)
        #print(c_f)
        c_f=np.delete(c_f,i,1)
        print(c_f)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[2 3]
 [8 9]]
[[2 3]
 [5 6]]
[[4 6]
 [7 9]]
[[1 3]
 [7 9]]
[[1 3]
 [4 6]]
[[4 5]
 [7 8]]
[[1 2]
 [7 8]]
[[1 2]
 [4 5]]


In [242]:
def inverse_matrix(a,xt=False):
    adj(a)
    adj_a=a_new
    det_a=np.linalg.det(a)
    
    #print(adj_a)
    #print(det_a)
    
    #checker
    if det_a==0:
        print("This matrix is not invertible")
        print(":(")
    else:
        inv_a=(1/det_a)*adj_a
        prod_unf=a*inv_a
        yeh=[]
        for i in range(a.shape[0]):
            for j in range(a.shape[0]):
                yeh.append(round(prod_unf[i,j]))
        prod=np.array(yeh).reshape((a.shape[0],a.shape[0]))
        if prod.all()==np.identity(a.shape[0]).all():
            #print(prod)
            print("This matrix is invertible")
            if xt==True:
                print("\n")
                print("{} is your original matrix".format(a))
                print("\n")
                print("{} is the adjunct of your matrix".format(adj_a))
                print("\n")
                print("{:.4g} is the determinant of your matrix".format(det_a))
            print("\n")
            print("{} is the inverse of your matrix".format(inv_a))
        else:
            print("This matrix is not invertible")
            print(":(")

In [243]:
n=np.matrix([[0.3,0.15,0.21,0.48],[1.42,0.46,1.16,0.91],[0.19,0.43,0.13,1.70],[1.28,0.53,1.41,0.28]])
inverse_matrix(n,True)

This matrix is invertible


[[0.3  0.15 0.21 0.48]
 [1.42 0.46 1.16 0.91]
 [0.19 0.43 0.13 1.7 ]
 [1.28 0.53 1.41 0.28]] is your original matrix


[[ 0.308654 -0.067788 -0.053286  0.014712]
 [ 0.797239 -0.213672 -0.121974  0.068295]
 [-0.541191  0.131616  0.087654 -0.032181]
 [-0.194766  0.051558  0.033072 -0.016458]] is the adjunct of your matrix


0.005044 is the determinant of your matrix


[[  61.18915361  -13.43864115  -10.56369021    2.91658241]
 [ 158.04875244  -42.35943429  -24.18075198   13.53915143]
 [-107.28848235   26.09223157   17.37697898   -6.37972666]
 [ -38.61141178   10.22112262    6.55636307   -3.26271842]] is the inverse of your matrix


In [247]:
w=np.matrix([[1,2],[3,4]])
e=np.matrix([[5],[6]])
print(w*e)

[[17]
 [39]]
